### ISSUE TITLE
Typo issue 

### ISSUE THREAD

**Issue by Helius01** [babaktaremi/Interview-Questions-Sample#1]
There is a typo issue in List vs LinkedList section.
Its Link vs LinkedList , it should be List vs LinkedList ig.

![image](https://github.com/user-attachments/assets/35102ee2-f62d-4d63-99f5-2a171219c5c5)

**Comment by Helius01** [comment]
![image](https://github.com/user-attachments/assets/fc92150e-7936-4256-bc67-c5a0999e7a8b)

You mean blow ?

**Comment by babaktaremi** [comment]
i meant ```below``` . thanks for pointing out!
